# mock_data.py
# Datos de las películas de XP Movies.

PELICULAS = [
    {
        "id": 1,
        "titulo": "El Padrino",
        "genero": "Drama",
        "clasificacion": "R",
        "duracion": "2h 55min",
        "descripcion": "La historia de la familia Corleone, una de las más poderosas del crimen organizado en Nueva York.",
        "imagen": "https://i.pinimg.com/1200x/74/f4/65/74f465d3ada4455e2f6defbe0fe11f67.jpg",
        "calificacion": 5.0,
        "tandas": ["4:00 PM", "7:00 PM", "10:00 PM"],
        "estado": "activa",
        "anio": 1972,
    },
    {
        "id": 2,
        "titulo": "Batman: El Caballero de la Noche",
        "genero": "Acción",
        "clasificacion": "PG-13",
        "duracion": "2h 32min",
        "descripcion": "Batman enfrenta al Joker, un criminal caótico que busca sumir Gotham City en el anarquismo total.",
        "imagen": "https://i.pinimg.com/736x/88/c8/20/88c8204e1017437290af9db9a02d83f6.jpg",
        "calificacion": 5.0,
        "tandas": ["3:30 PM", "6:30 PM", "9:30 PM"],
        "estado": "activa",
        "anio": 2008,
    },
    {
        "id": 3,
        "titulo": "Fight Club",
        "genero": "Thriller",
        "clasificacion": "R",
        "duracion": "2h 19min",
        "descripcion": "Un oficinista insomne forma un club de peleas clandestino con un carismático vendedor de jabón.",
        "imagen": "https://i.pinimg.com/736x/4b/5c/cb/4b5ccbe420a9061ea4564e82e0261548.jpg",
        "calificacion": 4.8,
        "tandas": ["5:00 PM", "8:00 PM", "11:00 PM"],
        "estado": "activa",
        "anio": 1999,
    },
    {
        "id": 4,
        "titulo": "Interstellar",
        "genero": "Ciencia Ficción",
        "clasificacion": "PG-13",
        "duracion": "2h 49min",
        "descripcion": "Un grupo de astronautas viaja a través de un agujero de gusano en busca de un nuevo hogar para la humanidad.",
        "imagen": "https://i.pinimg.com/736x/3f/09/dd/3f09ddcc1d3c3740f6a74e63d57fba61.jpg",
        "calificacion": 4.9,
        "tandas": ["4:30 PM", "7:30 PM", "10:30 PM"],
        "estado": "activa",
        "anio": 2014,
    },
    {
        "id": 5,
        "titulo": "The Truman Show",
        "genero": "Drama",
        "clasificacion": "PG",
        "duracion": "1h 43min",
        "descripcion": "Un hombre descubre que toda su vida ha sido un programa de televisión transmitido en vivo al mundo entero.",
        "imagen": "https://i.pinimg.com/1200x/e4/be/be/e4bebef03bf3c5a258f2069c25d1d1bc.jpg",
        "calificacion": 4.7,
        "tandas": ["3:00 PM", "6:00 PM", "9:00 PM"],
        "estado": "activa",
        "anio": 1998,
    },
    {
        "id": 6,
        "titulo": "The Butterfly Effect",
        "genero": "Ciencia Ficción",
        "clasificacion": "R",
        "duracion": "1h 53min",
        "descripcion": "Un joven descubre que puede viajar al pasado a través de sus recuerdos, pero cada cambio tiene consecuencias devastadoras.",
        "imagen": "https://i.pinimg.com/1200x/0b/21/17/0b2117529ba390b93dee98df45d30304.jpg",
        "calificacion": 4.5,
        "tandas": ["4:00 PM", "7:00 PM", "10:00 PM"],
        "estado": "activa",
        "anio": 2004,
    },
    {
        "id": 7,
        "titulo": "Forrest Gump",
        "genero": "Drama",
        "clasificacion": "PG-13",
        "duracion": "2h 22min",
        "descripcion": "La extraordinary historia de un hombre de Alabama cuya vida simple se cruza con los grandes eventos históricos del siglo XX.",
        "imagen": "https://i.pinimg.com/1200x/13/98/2a/13982aedfb82420cbcf1b44f616539f4.jpg",
        "calificacion": 4.9,
        "tandas": ["3:30 PM", "6:30 PM", "9:30 PM"],
        "estado": "activa",
        "anio": 1994,
    },
    {
        "id": 8,
        "titulo": "The Matrix",
        "genero": "Ciencia Ficción",
        "clasificacion": "R",
        "duracion": "2h 16min",
        "descripcion": "Un hacker descubre que la reality que conoce es una simulación creada por máquinas que esclavizan a la humanidad.",
        "imagen": "https://i.pinimg.com/736x/62/f2/41/62f241fd34d94f303a71df7fc7274fbb.jpg",
        "calificacion": 4.8,
        "tandas": ["5:00 PM", "8:00 PM", "11:00 PM"],
        "estado": "activa",
        "anio": 1999,
    },
]

PROXIMAS_PELICULAS = [
    {
        "id": 9,
        "titulo": "10 Things I Hate About You",
        "genero": "Romance",
        "clasificacion": "PG-13",
        "imagen": "https://i.pinimg.com/736x/fc/31/09/fc3109b7595900ec3709e4400db213ef.jpg",
        "estreno": "Próxima Semana",
    },
    {
        "id": 10,
        "titulo": "La La Land",
        "genero": "Romance",
        "clasificacion": "PG",
        "imagen": "https://i.pinimg.com/1200x/1a/5d/0f/1a5d0f456e6d4e474b3465ad030b1fdb.jpg",
        "estreno": "Próxima Semana",
    },
    {
        "id": 11,
        "titulo": "The Notebook",
        "genero": "Romance",
        "clasificacion": "PG-13",
        "imagen": "https://i.pinimg.com/736x/0a/8a/52/0a8a52c74e5e3d88d26925018c741be6.jpg",
        "estreno": "Próxima Semana",
    },
]
